### ISSUE TITLE
RC7 Upgrade

### ISSUE THREAD

**Issue by MaherJendoubi** [manekinekko/angular2-aot-demo#3]
Hi Wassim,

Would you please update this sample to RC7 if possible?

Best,
Maher

**Comment by manekinekko** [comment]
There is no RC7 in npm.

**Comment by MaherJendoubi** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/1798510/18482239/a1afb756-79df-11e6-919f-4a2dbbc3b41f.png)

**Comment by MaherJendoubi** [comment]
https://github.com/manekinekko/angular2-aot-demo/pull/5

**Comment by manekinekko** [comment]
Merged. Thanks.
